#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
from obstacle_detection.obstacle_detection_node import ObstacleDetectionNode

try:
    obstacle_detection_node = ObstacleDetectionNode()

    obstacle_detection_node.run()
except rospy.ROSInterruptException:
    pass
