#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
from beaverbot_pose.beaverbot_pose_node import BeaverbotPoseNode

try:
    beaverbot_pose_node = BeaverbotPoseNode()
    beaverbot_pose_node.run()
except rospy.ROSInterruptException:
    pass
