#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
from beaverbot_pose.rotation_angle_calibrator import RotationAngleCalibrator

try:
    rotation_angle_calibrator = RotationAngleCalibrator()
    rotation_angle_calibrator.run()
except rospy.ROSInterruptException:
    pass
