magnetic_declination_radians: 0.1382
yaw_offset: 0.0
zero_altitude: true
publish_filtered_gps: false

# Note: Uncomment the following lines to manually set the datum
# wait_for_datum: true
# use_odometry_yaw: true
# datum: [34.70242845166667, 137.408935105, -1.57, map, base_link]