#!/usr/bin/env python3
##
# @file calibrate
#
# @brief Provide a ROS node to calibrate the Beaverbot robot. This file is
# to hide the extension of a python script.
#
# @section author_doxygen_example Author(s)
# - Created by Tran Viet Thanh on 08/12/2024.
#
# Copyright (c) 2024 System Engineering Laboratory.  All rights reserved.

# External library
import rospy
from beaverbot_localization.calibrate import Calibrate


try:
    calibrate_node = Calibrate()

    calibrate_node.run()

except rospy.ROSInterruptException:
    pass
